ARG BASE_IMAGE_VERSION=2.1.2
ARG BASE_IMAGE=harbor.baai.ac.cn/flagos-base/flagos-base-nvidia-cuda12.8
FROM ${BASE_IMAGE}:${BASE_IMAGE_VERSION}
# 
ARG VENDOR=USE_NVIDIA
# workdir
WORKDIR /workspace
COPY . /workspace/FlagCX
WORKDIR /workspace/FlagCX

# build
RUN make ${VENDOR}=1
